/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1.vista;

import javax.swing.JOptionPane;
import proyecto1.controlador.ControladorDepartamento;
import proyecto1.controlador.ControladorRegion;

/**
 *
 * @author JD
 */
public class AccionesDepartamento extends javax.swing.JFrame {

    /**
     * Creates new form AccionesDepartamento
     */
    DepartamentoVista vistaD = new DepartamentoVista();
    ControladorDepartamento controladorD = new ControladorDepartamento();
    ControladorRegion controladorR = new ControladorRegion();
    String codigoE;
    String nombreE;
    
    public AccionesDepartamento() {
        initComponents();
        DatosRegion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        cmbRegion = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        lblTitulo = new javax.swing.JLabel();
        btnAccion = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtRegion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("CÓDIGO REGIÓN");

        cmbRegion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbRegionItemStateChanged(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("AGREGAR");
        lblTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnAccion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnAccion.setText("AGREGAR");
        btnAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccionActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("CÓDIGO");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("NOMBRE");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("REGIÓN");

        txtRegion.setEditable(false);
        txtRegion.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(cmbRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel4)
                        .addComponent(txtRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAccion)
                        .addGap(102, 102, 102)
                        .addComponent(btnCancelar)))
                .addGap(0, 73, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(cmbRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAccion)
                    .addComponent(btnCancelar))
                .addGap(48, 48, 48))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccionActionPerformed
        if(btnAccion.getText().equals("AGREGAR")) {
            if(ValidarTextField()) {
                if(!controladorD.ValidarCodigo(txtCodigo.getText())) {
                    if(!controladorD.ValidarDepartamento(txtNombre.getText())) {
                        controladorD.AgregarDepartamento((String)cmbRegion.getSelectedItem(), controladorR.ObtenerRegion((String)cmbRegion.getSelectedItem()), txtNombre.getText(), txtCodigo.getText());
                        JOptionPane.showMessageDialog(this, "Departamento agregado.");
                        this.setVisible(false);
                        vistaD.LlenarTabla();
                        vistaD.setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(this, "Ya existe un departamento con ese nombre.");
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "Ya existe un departamento con ese código.");
                }

            }
        } else if(btnAccion.getText().equals("EDITAR")) {
            if(ValidarTextField()) {
                if(!controladorD.ValidarCodigo(txtCodigo.getText()) || codigoE.equals(txtCodigo.getText())) {
                    if(!controladorD.ValidarDepartamento(txtNombre.getText()) || nombreE.equalsIgnoreCase(txtNombre.getText())) {
                        System.out.println(txtCodigo.getText()+"|"+codigoE+"|"+nombreE);
                        controladorD.EditarDepartamento(codigoE, nombreE, (String)cmbRegion.getSelectedItem(), controladorR.ObtenerRegion((String)cmbRegion.getSelectedItem()), txtNombre.getText(), txtCodigo.getText());
                        JOptionPane.showMessageDialog(this, "Kiosco editado");
                        this.setVisible(false);
                        vistaD.LlenarTabla();
                        vistaD.setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(this, "Ya existe un departamento con ese nombre.");
                    }
                    
                } else {
                    JOptionPane.showMessageDialog(this, "Ya existe un departamento con ese código.");
                }
            }
        }
    }//GEN-LAST:event_btnAccionActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        vistaD.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cmbRegionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbRegionItemStateChanged
        txtRegion.setText(controladorR.ObtenerRegion((String)cmbRegion.getSelectedItem()));
    }//GEN-LAST:event_cmbRegionItemStateChanged

    private boolean ValidarTextField() {
        if(txtCodigo.getText().isEmpty() || txtNombre.getText().isEmpty() || cmbRegion.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Debes rellenar todos los campos.");
            return false;
        }
        return true;
    }
    
    private void DatosRegion() {
        cmbRegion.addItem("SELECCIONA UNA REGIÓN");
        for(int i=0; i < controladorR.ObtenerRegiones().size(); i++) {
            cmbRegion.addItem(controladorR.ObtenerRegiones().get(i).getCodigo());
        }
    }
    
    public void Tipo(String tipo) {
        if(tipo.equals("AGREGAR")) {
            lblTitulo.setText("AGREGAR");
            btnAccion.setText("AGREGAR");
        } else if(tipo.equals("EDITAR")) {
            lblTitulo.setText("EDITAR");
            btnAccion.setText("EDITAR");
        }
    }
    
    public void CamposEditar(String codigo) {
        txtCodigo.setText(controladorD.ValidarSeleccion(codigo).getCodigoDepartamento());
        txtNombre.setText(controladorD.ValidarSeleccion(codigo).getNombre());
        cmbRegion.setSelectedItem(controladorD.ValidarSeleccion(codigo).getCodigoRegion());
        txtRegion.setText(controladorR.ObtenerRegion((String)cmbRegion.getSelectedItem()));
        codigoE = codigo;
        nombreE = txtNombre.getText();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccionesDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccionesDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccionesDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccionesDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccionesDepartamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccion;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cmbRegion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRegion;
    // End of variables declaration//GEN-END:variables
}
