/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1.vista;

import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import proyecto1.controlador.ControladorCompra;
import proyecto1.controlador.ControladorDatosFacturacion;
import proyecto1.controlador.ControladorDepartamento;
import proyecto1.controlador.ControladorMunicipio;
import proyecto1.controlador.ControladorRegion;
import proyecto1.controlador.ControladorTarjeta;
import proyecto1.controlador.ControladorUsuario;
import proyecto1.modelo.DatosFacturacion;
import proyecto1.modelo.Tarjetas;

/**
 *
 * @author JD
 */
public class MenuCliente extends javax.swing.JFrame {

    /**
     * Creates new form MenuCliente
     */
    ControladorUsuario controladorU = new ControladorUsuario();
    ControladorTarjeta controladorT = new ControladorTarjeta();
    ControladorDatosFacturacion controladorDF = new ControladorDatosFacturacion();
    ControladorDepartamento controladorD = new ControladorDepartamento();
    ControladorMunicipio controladorM = new ControladorMunicipio();
    ControladorCompra controladorC = new ControladorCompra();
    ControladorRegion controladorR = new ControladorRegion();
    
    public MenuCliente() {
        initComponents();
        //lblSaludo.setText("BIENVENID@ "+controladorU.UsuarioLogeado().getNombre().toUpperCase());
        tabbed.addTab("TARJETAS", panel1);
        tabbed.addTab("DATOS FACTURACIÓN", panel2);
        tabbed.addTab("COTIZACIÓN, PAGO Y FACTURA", panel3);
        tabbed.addTab("COMPRA", panel4);
        tabbed.addTab("ENVIOS", panel5);
        controladorT.TarjetasUsuario();
        LlenarTabla();
        controladorDF.DatosUsuario();
        LlenarTablaDatos();
        DatosComboboxDepartamento();
        ValoresRadio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipo = new javax.swing.ButtonGroup();
        tamanioP = new javax.swing.ButtonGroup();
        tipoServicio = new javax.swing.ButtonGroup();
        lblSaludo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tabbed = new javax.swing.JTabbedPane();
        panel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDF = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNombreD = new javax.swing.JTextField();
        txtApellidoD = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDireccionD = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtNITD = new javax.swing.JTextField();
        btnAgregarD = new javax.swing.JButton();
        panel4 = new javax.swing.JPanel();
        panel5 = new javax.swing.JPanel();
        panel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableT = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        opDebito = new javax.swing.JRadioButton();
        opCredito = new javax.swing.JRadioButton();
        panel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cmbDO = new javax.swing.JComboBox<>();
        cmbDD = new javax.swing.JComboBox<>();
        cmbMO = new javax.swing.JComboBox<>();
        cmbMD = new javax.swing.JComboBox<>();
        txtDO = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtDD = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        opPequenio = new javax.swing.JRadioButton();
        opMediano = new javax.swing.JRadioButton();
        opGrande = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        spinner = new javax.swing.JSpinner();
        btnCotizar = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        opEspecial = new javax.swing.JRadioButton();
        opEstandar = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblSaludo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblSaludo.setText("BIENVENIDA");

        jButton1.setText("CERRAR SESIÓN");
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("MENU PRINCIPAL");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("DATOS");

        tableDF.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NO.", "NOMBRE COMPLETO", "DIRECCIÓN", "NIT"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableDF.setEnabled(false);
        tableDF.setFocusable(false);
        jScrollPane2.setViewportView(tableDF);

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setText("NOMBRE: ");

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setText("APELLIDO:");

        txtNombreD.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtApellidoD.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setText("DIRECCIÓN:");

        txtDireccionD.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel11.setText("NIT:");

        txtNITD.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        btnAgregarD.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnAgregarD.setText("AGREGAR");
        btnAgregarD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(29, 29, 29)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombreD)
                            .addComponent(txtApellidoD, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNITD, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panel2Layout.createSequentialGroup()
                                    .addGap(90, 90, 90)
                                    .addComponent(jLabel3))
                                .addGroup(panel2Layout.createSequentialGroup()
                                    .addGap(41, 41, 41)
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtDireccionD, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 126, Short.MAX_VALUE))
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAgregarD)))
                .addContainerGap())
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(10, 10, 10)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtNombreD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtApellidoD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNITD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(39, 39, 39))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(txtDireccionD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addComponent(btnAgregarD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        tabbed.addTab("tab2", panel2);

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 819, Short.MAX_VALUE)
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 617, Short.MAX_VALUE)
        );

        tabbed.addTab("tab4", panel4);

        javax.swing.GroupLayout panel5Layout = new javax.swing.GroupLayout(panel5);
        panel5.setLayout(panel5Layout);
        panel5Layout.setHorizontalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 819, Short.MAX_VALUE)
        );
        panel5Layout.setVerticalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 617, Short.MAX_VALUE)
        );

        tabbed.addTab("tab5", panel5);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("MIS TARJETAS");

        tableT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NO.", "NOMBRE", "NUMERO", "TIPO", "FECHA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableT.setEnabled(false);
        tableT.setFocusable(false);
        jScrollPane1.setViewportView(tableT);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("NOMBRE:");

        txtFecha.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("NÚMERO:");

        txtNumero.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setText("FECHA:");

        txtNombre.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        btnAgregar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setText("TIPO:");

        tipo.add(opDebito);
        opDebito.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        opDebito.setText("Débito");

        tipo.add(opCredito);
        opCredito.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        opCredito.setText("Crédito");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(341, 341, 341)
                        .addComponent(jLabel2))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAgregar)
                            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panel1Layout.createSequentialGroup()
                                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addGap(26, 26, 26)
                                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtNumero)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(84, 84, 84)
                                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(panel1Layout.createSequentialGroup()
                                            .addComponent(opDebito)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(opCredito))))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(btnAgregar)
                .addGap(1, 1, 1)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(opDebito)
                    .addComponent(opCredito))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        tabbed.addTab("tab1", panel1);

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel12.setText("Cotización");

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel13.setText("ORIGEN");

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel14.setText("DESTINO");

        cmbDO.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cmbDO.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbDOItemStateChanged(evt);
            }
        });

        cmbDD.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cmbDD.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbDDItemStateChanged(evt);
            }
        });

        cmbMO.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        cmbMD.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        txtDO.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel15.setText("DIRECCIÓN");

        jLabel16.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel16.setText("DIRECCIÓN");

        txtDD.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel17.setText("TAMAÑO PAQUETE");

        tamanioP.add(opPequenio);
        opPequenio.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        opPequenio.setText("Pequeño");

        tamanioP.add(opMediano);
        opMediano.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        opMediano.setText("Mediano");

        tamanioP.add(opGrande);
        opGrande.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        opGrande.setText("Grande");

        jLabel18.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel18.setText("CANTIDAD DE PAQUETES");

        spinner.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        btnCotizar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnCotizar.setText("COTIZAR");
        btnCotizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCotizarActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel19.setText("TIPO DE SERVICIO");

        tipoServicio.add(opEspecial);
        opEspecial.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        opEspecial.setText("Especial (Q 00.00)");

        tipoServicio.add(opEstandar);
        opEstandar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        opEstandar.setText("Estándar (Q 00.00)");

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtDO, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cmbMO, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel3Layout.createSequentialGroup()
                            .addGap(36, 36, 36)
                            .addComponent(jLabel13))
                        .addComponent(cmbDO, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(btnCotizar, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(174, 174, 174))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                                .addComponent(spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(204, 204, 204))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                                .addComponent(opPequenio)
                                .addGap(18, 18, 18)
                                .addComponent(opMediano)
                                .addGap(18, 18, 18)
                                .addComponent(opGrande)
                                .addGap(121, 121, 121))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(179, 179, 179))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                                .addComponent(opEstandar)
                                .addGap(18, 18, 18)
                                .addComponent(opEspecial)
                                .addGap(106, 106, 106)))))
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addGap(36, 36, 36))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cmbMD, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbDD, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtDD, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap(328, Short.MAX_VALUE)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(365, 365, 365))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(321, 321, 321))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(opPequenio)
                            .addComponent(opMediano)
                            .addComponent(opGrande))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(cmbMD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(11, 11, 11)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(opEspecial)
                            .addComponent(opEstandar)))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbDO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(cmbMO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addComponent(btnCotizar)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(318, Short.MAX_VALUE))
        );

        tabbed.addTab("tab3", panel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabbed)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(194, 194, 194)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(378, 378, 378)
                .addComponent(lblSaludo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSaludo)
                .addGap(12, 12, 12)
                .addComponent(tabbed)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed

    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed

    }//GEN-LAST:event_txtNumeroActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed

    }//GEN-LAST:event_txtFechaActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String tipo;
        if(ValidarTextField()) {
            if(opDebito.isSelected()) {
                tipo = opDebito.getText();
            } else {
                tipo = opCredito.getText();
            }
            
            if(!controladorT.ValidarTarjeta(txtNumero.getText())) {
                if(txtNumero.getText().length() >= 8) {
                    controladorT.CrearTarjeta(txtNombre.getText(), tipo, txtNumero.getText(), txtFecha.getText());
                    JOptionPane.showMessageDialog(this, "Tarjeta agregada.");
                    LimpiarTextField();
                    controladorT.TarjetasUsuario();
                    LlenarTabla();
                } else {
                    JOptionPane.showMessageDialog(this, "El número de tarjeta debe tener mas de 8 digitos.");
                }
                
            } else {
                JOptionPane.showMessageDialog(this, "Ya existe esa tarjeta.");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Debes rellenar todos los campos");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnAgregarDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarDActionPerformed
        if(ValidarCampos()) {
            if(!controladorDF.ValidarDatos(txtDireccionD.getText())) {
                controladorDF.AgregarDatos(txtNombreD.getText(), txtApellidoD.getText(), txtDireccionD.getText(), txtNITD.getText());
                JOptionPane.showMessageDialog(this, "Datos agregados.");
                LimpiarTextField();
                controladorDF.DatosUsuario();
                LlenarTablaDatos();
            } else {
                JOptionPane.showMessageDialog(this, "Ya existe esa dirección.");
            }
        }else {
            JOptionPane.showMessageDialog(this, "Debes rellenar todos los campos");
        }
    }//GEN-LAST:event_btnAgregarDActionPerformed

    private void cmbDOItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbDOItemStateChanged
        DatosComboboxMunicipio(cmbMO, (String)cmbDO.getSelectedItem());
    }//GEN-LAST:event_cmbDOItemStateChanged

    private void cmbDDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbDDItemStateChanged
        DatosComboboxMunicipio(cmbMD, (String)cmbDD.getSelectedItem());
        PrecioServicio();
        
    }//GEN-LAST:event_cmbDDItemStateChanged

    private void btnCotizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCotizarActionPerformed
        if(ValidarCamposCotizar()) {
            JOptionPane.showMessageDialog(this, "El total seria: "+controladorC.Cotizar((String)cmbDO.getSelectedItem(), (String)cmbMO.getSelectedItem(), txtDO.getText(), (String)cmbDD.getSelectedItem(), (String)cmbMD.getSelectedItem(), txtDD.getText(), String.valueOf(spinner.getValue()), tamanioP.getSelection().getActionCommand(), tipoServicio.getSelection().getActionCommand()));
        } else {
            JOptionPane.showMessageDialog(this, "Debes rellenar todos los campos");
        }
        
    }//GEN-LAST:event_btnCotizarActionPerformed
     
    // METODOS PARA TARJETAS
    private boolean ValidarTextField() {
        if(!txtNombre.getText().isEmpty() && !txtNumero.getText().isEmpty() && !txtFecha.getText().isEmpty() && (opDebito.isSelected() || opCredito.isSelected())) {
            return true;
        }
        return false;
    }
    
    private void LimpiarTextField() {
        txtNombre.setText("");
        txtNumero.setText("");
        txtFecha.setText("");
        tipo.clearSelection();
        txtNombreD.setText("");
        txtApellidoD.setText("");
        txtDireccionD.setText("");
        txtNITD.setText("");
    }
    
    private void LlenarTabla() {
        DefaultTableModel modelo = new DefaultTableModel(new String[]{"NO.", "NOMBRE", "NUMERO", "TIPO", "FECHA"}, controladorT.ObtenerTarjetasUsuario().size());
        tableT.setModel(modelo);
        
        TableModel modeloDatos = tableT.getModel();
        for(int i = 0; i < controladorT.ObtenerTarjetasUsuario().size(); i++) {
            Tarjetas tarjeta = controladorT.ObtenerTarjetasUsuario().get(i);
            modeloDatos.setValueAt(i+1, i, 0);
            modeloDatos.setValueAt(tarjeta.getNombre(), i, 1);
            modeloDatos.setValueAt(tarjeta.getNumero(), i, 2);
            modeloDatos.setValueAt(tarjeta.getTipo(), i, 3);
            modeloDatos.setValueAt(tarjeta.getFecha(), i, 4);
        }  
    }
    
    // METODOS PARA DATOS FACTURACION
    
    private boolean ValidarCampos() {
        if(!txtNombreD.getText().isEmpty() && !txtApellidoD.getText().isEmpty() && !txtDireccionD.getText().isEmpty() && !txtNITD.getText().isEmpty()) {
            return true;
        }
        return false;
    }
    
    private void LlenarTablaDatos() {
        DefaultTableModel modelo = new DefaultTableModel(new String[]{"NO.", "NOMBRE COMPLETO", "DIRECCIÖN", "NIT"}, controladorDF.ObtenerDatos().size());
        tableDF.setModel(modelo);
        
        TableModel modeloDatos = tableDF.getModel();
        for(int i = 0; i < controladorDF.ObtenerDatos().size(); i++) {
            DatosFacturacion datos = controladorDF.ObtenerDatos().get(i);
            modeloDatos.setValueAt(i+1, i, 0);
            modeloDatos.setValueAt(datos.getNombre()+" "+datos.getApellido(), i, 1);
            modeloDatos.setValueAt(datos.getDireccion(), i, 2);
            modeloDatos.setValueAt(datos.getNit(), i, 3);
        }  
    }
    
    // METODOS PARA COTIZACIÓN
    
    private void DatosComboboxDepartamento() {
        cmbDO.addItem("DEPARTAMENTO");
        cmbDD.addItem("DEPARTAMENTO");
        //if(!cmbMO.getItemAt(0).equals("MUNICIPIO") || !cmbMD.getItemAt(0).equals("MUNICIPIO")) {
            cmbMO.addItem("MUNICIPIO");
            cmbMD.addItem("MUNICIPIO");
        //}

        for(int i=0; i < controladorD.ObtenerDepartamento().size(); i++) {
            cmbDO.addItem(controladorD.ObtenerDepartamento().get(i).getNombre());
            cmbDD.addItem(controladorD.ObtenerDepartamento().get(i).getNombre());
        }
    }
    
    private void DatosComboboxMunicipio(JComboBox cmb, String nombre) {
        
        if(!nombre.equals("DEPARTAMENTO")) {
            cmb.removeAllItems();
            cmb.addItem("MUNICIPIO");
            String codigoD = controladorD.ObtenerDepartamentoNombre(nombre).getCodigoDepartamento();
            controladorM.MunicipiosPorDepartamento(codigoD);
            for(int i=0; i < controladorM.ObtenerMunicipios().size(); i++) {
                cmb.addItem(controladorM.ObtenerMunicipios().get(i).getNombre());
            }
            
        } else {
            cmb.removeAllItems();
            cmb.addItem("MUNICIPIO");
        }
        
    }
    
    private boolean ValidarCamposCotizar() {
        if(cmbDO.getSelectedIndex() != 0 && cmbMO.getSelectedIndex() != 0 && !txtDO.getText().isEmpty() && cmbDD.getSelectedIndex() != 0 && cmbMD.getSelectedIndex() != 0 && (Integer)spinner.getValue() >= 1 && (opPequenio.isSelected() || opMediano.isSelected() || opGrande.isSelected()) && (tipoServicio.getSelection() != null)) {
            return true;
        }
        return false;
    }
    
    private void ValoresRadio() {
        opPequenio.setActionCommand("Pequeño");
        opMediano.setActionCommand("Mediano");
        opGrande.setActionCommand("Grande");
        opEstandar.setActionCommand("Estándar");
        opEspecial.setActionCommand("Especial");
        
    }   
    
    private void PrecioServicio() {
        if(!cmbDD.getSelectedItem().equals("DEPARTAMENTO")) {
            opEstandar.setText("Estándar (Q "+controladorR.ObtenerRegionSeleccionada(controladorD.ObtenerDepartamentoNombre((String)cmbDD.getSelectedItem()).getCodigoRegion()).getEstandar()+")");
            opEspecial.setText("Especial (Q "+controladorR.ObtenerRegionSeleccionada(controladorD.ObtenerDepartamentoNombre((String)cmbDD.getSelectedItem()).getCodigoRegion()).getEspecial()+")");
        }
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregarD;
    private javax.swing.JButton btnCotizar;
    private javax.swing.JComboBox<String> cmbDD;
    private javax.swing.JComboBox<String> cmbDO;
    private javax.swing.JComboBox<String> cmbMD;
    private javax.swing.JComboBox<String> cmbMO;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblSaludo;
    private javax.swing.JRadioButton opCredito;
    private javax.swing.JRadioButton opDebito;
    private javax.swing.JRadioButton opEspecial;
    private javax.swing.JRadioButton opEstandar;
    private javax.swing.JRadioButton opGrande;
    private javax.swing.JRadioButton opMediano;
    private javax.swing.JRadioButton opPequenio;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JPanel panel4;
    private javax.swing.JPanel panel5;
    private javax.swing.JSpinner spinner;
    private javax.swing.JTabbedPane tabbed;
    private javax.swing.JTable tableDF;
    private javax.swing.JTable tableT;
    private javax.swing.ButtonGroup tamanioP;
    private javax.swing.ButtonGroup tipo;
    private javax.swing.ButtonGroup tipoServicio;
    private javax.swing.JTextField txtApellidoD;
    private javax.swing.JTextField txtDD;
    private javax.swing.JTextField txtDO;
    private javax.swing.JTextField txtDireccionD;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNITD;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreD;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
