/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1.vista;

import java.awt.Component;
import java.awt.Container;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import proyecto1.controlador.ControladorCompra;
import proyecto1.controlador.ControladorDatosFacturacion;
import proyecto1.controlador.ControladorDepartamento;
import proyecto1.controlador.ControladorMunicipio;
import proyecto1.controlador.ControladorRegion;
import proyecto1.controlador.ControladorTarjeta;
import proyecto1.controlador.ControladorUsuario;
import proyecto1.modelo.Compras;
import proyecto1.modelo.DatosFacturacion;
import proyecto1.modelo.Tarjetas;

/**
 *
 * @author JD
 */
public class MenuCliente extends javax.swing.JFrame {

    /**
     * Creates new form MenuCliente
     */
    ControladorUsuario controladorU = new ControladorUsuario();
    ControladorTarjeta controladorT = new ControladorTarjeta();
    ControladorDatosFacturacion controladorDF = new ControladorDatosFacturacion();
    ControladorDepartamento controladorD = new ControladorDepartamento();
    ControladorMunicipio controladorM = new ControladorMunicipio();
    ControladorCompra controladorC = new ControladorCompra();
    ControladorRegion controladorR = new ControladorRegion();
    String totalcotizar;
    String totalC;
    String datosFE;
    ImageIcon image;
    
    public MenuCliente() {
        initComponents();
        lblSaludo.setText("BIENVENID@ "+controladorU.UsuarioLogeado().getNombre().toUpperCase());
        tabbed.addTab("TARJETAS", panel1);
        tabbed.addTab("DATOS FACTURACIÓN", panel2);
        tabbed.addTab("COTIZACIÓN, PAGO Y FACTURA", panel3);
        tabbed.addTab("ENVIOS", panel4);
        controladorT.TarjetasUsuario();
        LlenarTabla();
        controladorDF.DatosUsuario();
        LlenarTablaDatos();
        DatosIniciales();
        ValoresRadio();
        HabilitarPanel(panelPago, false);
        controladorC.GuardarComprasUsuario();
        LlenarTablaEnvios();
        setImageLabel(lblImagen, controladorU.UsuarioLogeado().getFoto());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipo = new javax.swing.ButtonGroup();
        tamanioP = new javax.swing.ButtonGroup();
        tipoServicio = new javax.swing.ButtonGroup();
        tipoPago = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblSaludo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tabbed = new javax.swing.JTabbedPane();
        panel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDF = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNombreD = new javax.swing.JTextField();
        txtApellidoD = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDireccionD = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtNITD = new javax.swing.JTextField();
        btnAgregarD = new javax.swing.JButton();
        btnCancelarDF = new javax.swing.JButton();
        panel4 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableE = new javax.swing.JTable();
        btnFactura = new javax.swing.JButton();
        btnGuia = new javax.swing.JButton();
        btnCancelarEnvio = new javax.swing.JButton();
        panel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableT = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        opDebito = new javax.swing.JRadioButton();
        opCredito = new javax.swing.JRadioButton();
        panel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cmbDO = new javax.swing.JComboBox<>();
        cmbDD = new javax.swing.JComboBox<>();
        cmbMO = new javax.swing.JComboBox<>();
        cmbMD = new javax.swing.JComboBox<>();
        txtDO = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtDD = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        opPequenio = new javax.swing.JRadioButton();
        opMediano = new javax.swing.JRadioButton();
        opGrande = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        spinner = new javax.swing.JSpinner();
        btnCotizar = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        opEspecial = new javax.swing.JRadioButton();
        opEstandar = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        panelPago = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        opPContraEntrega = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        opPConTarjeta = new javax.swing.JRadioButton();
        lblTarjeta = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        cmbDatosF = new javax.swing.JComboBox<>();
        btnPago = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        cmbTarjeta = new javax.swing.JComboBox<>();
        txtCVV = new javax.swing.JTextField();
        lblCVV = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnDescargarC = new javax.swing.JButton();
        lblImagen = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblSaludo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblSaludo.setText("BIENVENIDA");

        jButton1.setText("CERRAR SESIÓN");
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("MENU PRINCIPAL");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("DATOS");

        tableDF.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NO.", "NOMBRE COMPLETO", "DIRECCIÓN", "NIT"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableDF.setFocusable(false);
        tableDF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDFMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableDF);

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setText("NOMBRE: ");

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setText("APELLIDO:");

        txtNombreD.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtApellidoD.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setText("DIRECCIÓN:");

        txtDireccionD.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel11.setText("NIT:");

        txtNITD.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        btnAgregarD.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnAgregarD.setText("AGREGAR");
        btnAgregarD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarDActionPerformed(evt);
            }
        });

        btnCancelarDF.setText("CANCELAR");
        btnCancelarDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(29, 29, 29)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombreD)
                            .addComponent(txtApellidoD, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNITD, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panel2Layout.createSequentialGroup()
                                    .addGap(90, 90, 90)
                                    .addComponent(jLabel3))
                                .addGroup(panel2Layout.createSequentialGroup()
                                    .addGap(41, 41, 41)
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtDireccionD, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAgregarD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancelarDF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(10, 10, 10)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtNombreD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtApellidoD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNITD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(39, 39, 39))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(txtDireccionD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addComponent(btnAgregarD)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelarDF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        tabbed.addTab("tab2", panel2);

        jLabel24.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel24.setText("ENVÍOS");

        tableE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NO.", "CÓDIGO", "TIPO DE SERVICIO", "DEPARTAMENTO DESTINO", "MUNICIPIO DESTINO", "TIPO DE PAGO", "TOTAL DE ENVIÍO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableEMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableE);

        btnFactura.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnFactura.setText("DESCARGAR FACTURA");
        btnFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturaActionPerformed(evt);
            }
        });

        btnGuia.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnGuia.setText("DESCARGAR GUÍA");
        btnGuia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuiaActionPerformed(evt);
            }
        });

        btnCancelarEnvio.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnCancelarEnvio.setText("CANCELAR");
        btnCancelarEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEnvioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3))
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel4Layout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addComponent(btnFactura)
                                .addGap(83, 83, 83)
                                .addComponent(btnGuia, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel4Layout.createSequentialGroup()
                                .addGap(381, 381, 381)
                                .addComponent(jLabel24)))
                        .addGap(0, 202, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancelarEnvio)))
                .addContainerGap())
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelarEnvio)
                        .addContainerGap(94, Short.MAX_VALUE))
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuia)
                            .addComponent(btnFactura))
                        .addGap(28, 28, 28))))
        );

        tabbed.addTab("tab4", panel4);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("MIS TARJETAS");

        tableT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NO.", "NOMBRE", "NUMERO", "TIPO", "FECHA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableT.setEnabled(false);
        tableT.setFocusable(false);
        jScrollPane1.setViewportView(tableT);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("NOMBRE:");

        txtFecha.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("NÚMERO:");

        txtNumero.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setText("FECHA:");

        txtNombre.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        btnAgregar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setText("TIPO:");

        tipo.add(opDebito);
        opDebito.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        opDebito.setText("Débito");

        tipo.add(opCredito);
        opCredito.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        opCredito.setText("Crédito");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(341, 341, 341)
                        .addComponent(jLabel2))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAgregar)
                            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panel1Layout.createSequentialGroup()
                                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addGap(26, 26, 26)
                                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtNumero)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(84, 84, 84)
                                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(panel1Layout.createSequentialGroup()
                                            .addComponent(opDebito)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(opCredito))))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(btnAgregar)
                .addGap(1, 1, 1)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(opDebito)
                    .addComponent(opCredito))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        tabbed.addTab("tab1", panel1);

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel12.setText("Cotización");

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel13.setText("ORIGEN");

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel14.setText("DESTINO");

        cmbDO.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cmbDO.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbDOItemStateChanged(evt);
            }
        });

        cmbDD.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cmbDD.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbDDItemStateChanged(evt);
            }
        });

        cmbMO.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        cmbMD.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        txtDO.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel15.setText("DIRECCIÓN");

        jLabel16.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel16.setText("DIRECCIÓN");

        txtDD.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel17.setText("TAMAÑO PAQUETE");

        tamanioP.add(opPequenio);
        opPequenio.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        opPequenio.setText("Pequeño");

        tamanioP.add(opMediano);
        opMediano.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        opMediano.setText("Mediano");

        tamanioP.add(opGrande);
        opGrande.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        opGrande.setText("Grande");

        jLabel18.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel18.setText("CANTIDAD DE PAQUETES");

        spinner.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        btnCotizar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnCotizar.setText("COTIZAR");
        btnCotizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCotizarActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel19.setText("TIPO DE SERVICIO");

        tipoServicio.add(opEspecial);
        opEspecial.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        opEspecial.setText("Especial (Q 00.00)");

        tipoServicio.add(opEstandar);
        opEstandar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        opEstandar.setText("Estándar (Q 00.00)");

        panelPago.setEnabled(false);

        jLabel21.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel21.setText("TIPO DE PAGO");

        tipoPago.add(opPContraEntrega);
        opPContraEntrega.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        opPContraEntrega.setText("Pago contra entrega");
        opPContraEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opPContraEntregaActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel22.setText("Cobro adicional de Q 5.00");

        tipoPago.add(opPConTarjeta);
        opPConTarjeta.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        opPConTarjeta.setText("Pago con tarjeta");
        opPConTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opPConTarjetaActionPerformed(evt);
            }
        });

        lblTarjeta.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblTarjeta.setText("TARJETA");

        jLabel20.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel20.setText("PAGO");

        jLabel23.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel23.setText("DATOS DE FACTURACIÓN");

        cmbDatosF.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        btnPago.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnPago.setText("REALIZAR PAGO");
        btnPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagoActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtCVV.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        lblCVV.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblCVV.setText("CVV (3 Digitos)");

        lblTotal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelPagoLayout = new javax.swing.GroupLayout(panelPago);
        panelPago.setLayout(panelPagoLayout);
        panelPagoLayout.setHorizontalGroup(
            panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPagoLayout.createSequentialGroup()
                .addGroup(panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPagoLayout.createSequentialGroup()
                        .addGroup(panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(opPContraEntrega)
                            .addGroup(panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cmbTarjeta, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelPagoLayout.createSequentialGroup()
                                    .addGap(21, 21, 21)
                                    .addComponent(jLabel22)))
                            .addComponent(lblTarjeta))
                        .addGap(107, 107, 107)
                        .addGroup(panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCVV)
                            .addComponent(txtCVV, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbDatosF, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel21))
                .addGap(159, 159, 159)
                .addGroup(panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPago, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
                .addGap(35, 35, 35))
            .addGroup(panelPagoLayout.createSequentialGroup()
                .addGroup(panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPagoLayout.createSequentialGroup()
                        .addGap(366, 366, 366)
                        .addComponent(jLabel20))
                    .addComponent(opPConTarjeta)
                    .addGroup(panelPagoLayout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPagoLayout.setVerticalGroup(
            panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPagoLayout.createSequentialGroup()
                .addComponent(jLabel20)
                .addGap(3, 3, 3)
                .addGroup(panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opPContraEntrega)
                    .addComponent(cmbDatosF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(btnPago))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(opPConTarjeta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCVV)
                        .addComponent(btnCancelar))
                    .addComponent(lblTarjeta))
                .addGap(20, 20, 20)
                .addGroup(panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCVV, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnDescargarC.setText("DESCARGAR COTIZACIÓN");
        btnDescargarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescargarCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(321, 321, 321))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                        .addComponent(btnCotizar, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(289, 289, 289))))
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addComponent(btnDescargarC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addGap(365, 365, 365))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(54, 54, 54))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtDO, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmbMO, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel3Layout.createSequentialGroup()
                                    .addGap(36, 36, 36)
                                    .addComponent(jLabel13))
                                .addComponent(cmbDO, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(174, 174, 174))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                                .addComponent(spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(204, 204, 204))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                                .addComponent(opPequenio)
                                .addGap(18, 18, 18)
                                .addComponent(opMediano)
                                .addGap(18, 18, 18)
                                .addComponent(opGrande)
                                .addGap(121, 121, 121))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(179, 179, 179))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                                .addComponent(opEstandar)
                                .addGap(18, 18, 18)
                                .addComponent(opEspecial)
                                .addGap(106, 106, 106)))
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addGap(36, 36, 36))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cmbMD, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbDD, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtDD, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47))))
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(btnDescargarC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(opPequenio)
                            .addComponent(opMediano)
                            .addComponent(opGrande))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(cmbMD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(11, 11, 11)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(opEspecial)
                            .addComponent(opEstandar)))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbDO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(cmbMO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addComponent(btnCotizar)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbed.addTab("tab3", panel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabbed)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(194, 194, 194)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(366, 366, 366)
                                .addComponent(lblSaludo)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSaludo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(tabbed)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        LimpiarTextFieldCotizar();
        lblTotal.setText("");
        lblTarjeta.setVisible(false);
        cmbTarjeta.setVisible(false);
        lblCVV.setVisible(false);
        txtCVV.setVisible(false);
        btnCancelar.setVisible(false);
        btnDescargarC.setVisible(false);
        HabilitarPanel(panelPago, false);
        opEstandar.setText("Estándar (Q 00.00)");
        opEspecial.setText("Especial (Q 00.00)");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagoActionPerformed
        if(ValidarCamposPago()) {
            controladorC.RealizarCompra((String)cmbDO.getSelectedItem(), (String)cmbMO.getSelectedItem(), txtDO.getText(), (String)cmbDD.getSelectedItem(), (String)cmbMD.getSelectedItem(), txtDD.getText(), String.valueOf(spinner.getValue()), tamanioP.getSelection().getActionCommand(), tipoPago.getSelection().getActionCommand(), (String)cmbTarjeta.getSelectedItem(), tipoServicio.getSelection().getActionCommand(), (String)cmbDatosF.getSelectedItem());
            JOptionPane.showMessageDialog(this, "Pago realizado. Puedes descargar tu factura o guía en la sección de envios.");
            controladorC.GuardarComprasUsuario();
            LlenarTablaEnvios();
            LimpiarTextFieldCotizar();
            lblTotal.setText("");
            lblTarjeta.setVisible(false);
            cmbTarjeta.setVisible(false);
            lblCVV.setVisible(false);
            txtCVV.setVisible(false);
            btnCancelar.setVisible(false);
            btnDescargarC.setVisible(false);
            opEstandar.setText("Estándar (Q 00.00)");
            opEspecial.setText("Especial (Q 00.00)");
            HabilitarPanel(panelPago, false);
        } else {
            JOptionPane.showMessageDialog(this, "Debes rellenar todos los campos.");
        }

    }//GEN-LAST:event_btnPagoActionPerformed

    private void opPConTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opPConTarjetaActionPerformed
        lblTarjeta.setVisible(true);
        cmbTarjeta.setVisible(true);
        lblCVV.setVisible(true);
        txtCVV.setVisible(true);
        lblTotal.setText("TOTAL: Q "+totalcotizar);
    }//GEN-LAST:event_opPConTarjetaActionPerformed

    private void opPContraEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opPContraEntregaActionPerformed
        lblTarjeta.setVisible(false);
        cmbTarjeta.setVisible(false);
        lblCVV.setVisible(false);
        txtCVV.setVisible(false);
        totalC = String.valueOf(Double.parseDouble(totalcotizar)+5);
        lblTotal.setText("TOTAL: Q "+totalC);
    }//GEN-LAST:event_opPContraEntregaActionPerformed

    private void btnCotizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCotizarActionPerformed
        if(ValidarCamposCotizar()) {
            totalcotizar = controladorC.Cotizar((String)cmbDO.getSelectedItem(), (String)cmbMO.getSelectedItem(), txtDO.getText(), (String)cmbDD.getSelectedItem(), (String)cmbMD.getSelectedItem(), txtDD.getText(), String.valueOf(spinner.getValue()), tamanioP.getSelection().getActionCommand(), tipoServicio.getSelection().getActionCommand());
            JOptionPane.showMessageDialog(this, "El total seria: Q "+totalcotizar);
            lblTotal.setText("TOTAL: Q "+totalcotizar);
            totalC = totalcotizar;
            HabilitarPanel(panelPago, true);
            btnDescargarC.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Debes rellenar todos los campos.");
        }

    }//GEN-LAST:event_btnCotizarActionPerformed

    private void cmbDDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbDDItemStateChanged
        DatosComboboxMunicipio(cmbMD, (String)cmbDD.getSelectedItem());
        PrecioServicio();

    }//GEN-LAST:event_cmbDDItemStateChanged

    private void cmbDOItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbDOItemStateChanged
        DatosComboboxMunicipio(cmbMO, (String)cmbDO.getSelectedItem());
    }//GEN-LAST:event_cmbDOItemStateChanged

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String tipo;
        if(ValidarTextField()) {
            if(opDebito.isSelected()) {
                tipo = opDebito.getText();
            } else {
                tipo = opCredito.getText();
            }

            if(!controladorT.ValidarTarjeta(txtNumero.getText())) {
                if(txtNumero.getText().length() >= 8) {
                    controladorT.CrearTarjeta(txtNombre.getText(), tipo, txtNumero.getText(), txtFecha.getText());
                    JOptionPane.showMessageDialog(this, "Tarjeta agregada.");
                    LimpiarTextField();
                    controladorT.TarjetasUsuario();
                    LlenarTabla();
                    DatosTarjeta();
                } else {
                    JOptionPane.showMessageDialog(this, "El número de tarjeta debe tener mas de 8 digitos.");
                }

            } else {
                JOptionPane.showMessageDialog(this, "Ya existe esa tarjeta.");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Debes rellenar todos los campos.");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed

    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed

    }//GEN-LAST:event_txtNumeroActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed

    }//GEN-LAST:event_txtFechaActionPerformed

    private void btnAgregarDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarDActionPerformed
        if(btnAgregarD.getText().equals("AGREGAR")) {
            if(ValidarCampos()) {
                if(!controladorDF.ValidarDatos(txtDireccionD.getText())) {
                    controladorDF.AgregarDatos(txtNombreD.getText(), txtApellidoD.getText(), txtDireccionD.getText(), txtNITD.getText());
                    JOptionPane.showMessageDialog(this, "Datos agregados.");
                    LimpiarTextField();
                    controladorDF.DatosUsuario();
                    LlenarTablaDatos();
                    DatosFacturacion();
                } else {
                    JOptionPane.showMessageDialog(this, "Ya existe esa dirección.");
                }
            }else {
                JOptionPane.showMessageDialog(this, "Debes rellenar todos los campos.");
            }
        } else if(btnAgregarD.getText().equals("EDITAR")) {
            if(ValidarCampos()) {
                if(!controladorDF.ValidarDatos(txtDireccionD.getText()) || datosFE.equals(txtDireccionD.getText())) {
                    controladorDF.EditarDato((String)tableDF.getValueAt(tableDF.getSelectedRow(), 1),(String)tableDF.getValueAt(tableDF.getSelectedRow(), 2), (String)tableDF.getValueAt(tableDF.getSelectedRow(), 3), txtNombreD.getText(), txtApellidoD.getText(), txtDireccionD.getText(), txtNITD.getText());
                    JOptionPane.showMessageDialog(this, "Datos editados.");
                    LimpiarTextField();
                    controladorDF.DatosUsuario();
                    LlenarTablaDatos();
                    DatosFacturacion();
                    btnAgregarD.setText("AGREGAR");
                    btnCancelarDF.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(this, "Ya existe esa dirección.");
                }
            }else {
                JOptionPane.showMessageDialog(this, "Debes rellenar todos los campos.");
            }
        }        
    }//GEN-LAST:event_btnAgregarDActionPerformed

    private void btnDescargarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescargarCActionPerformed
        controladorC.DescargarCotizacion((String)cmbDO.getSelectedItem(), (String)cmbMO.getSelectedItem(), (String)cmbDD.getSelectedItem(), (String)cmbMD.getSelectedItem(), String.valueOf(spinner.getValue()), tamanioP.getSelection().getActionCommand(), tipoServicio.getSelection().getActionCommand());
        int response = JOptionPane.showConfirmDialog(this, "PDF creado. ¿Deseas abrir el PDF?", "PDF", JOptionPane.YES_NO_OPTION);
            
        if(response == JOptionPane.YES_OPTION) {
             controladorC.AbrirPDF();
        }
        /*LimpiarTextFieldCotizar();
        btnDescargarC.setVisible(false);*/
    }//GEN-LAST:event_btnDescargarCActionPerformed

    private void btnFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturaActionPerformed
        controladorC.GenerarFactura((String)tableE.getValueAt(tableE.getSelectedRow(), 1));
        JOptionPane.showMessageDialog(this, "Factura generada. Puedes ver el archivo en la carpeta documentos/facturas");
    }//GEN-LAST:event_btnFacturaActionPerformed

    private void btnGuiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuiaActionPerformed
        controladorC.GenerarGuia((String)tableE.getValueAt(tableE.getSelectedRow(), 1));
        JOptionPane.showMessageDialog(this, "Guía generada. Puedes ver el archivo en la carpeta documentos/guias");
    }//GEN-LAST:event_btnGuiaActionPerformed

    private void tableEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableEMouseClicked
       if(tableE.getSelectedRow() >= 0) {
            btnGuia.setVisible(true);
            btnFactura.setVisible(true);
            btnCancelarEnvio.setVisible(true);
        }
    }//GEN-LAST:event_tableEMouseClicked

    private void btnCancelarEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEnvioActionPerformed
        btnGuia.setVisible(false);
        btnFactura.setVisible(false);
        btnCancelarEnvio.setVisible(false);
        tableE.clearSelection();
    }//GEN-LAST:event_btnCancelarEnvioActionPerformed

    private void tableDFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDFMouseClicked
        if(tableDF.getSelectedRow() >= 0) {
            DatosFacturacion df = controladorDF.ObtenerDato((String)tableDF.getValueAt(tableDF.getSelectedRow(), 1),(String)tableDF.getValueAt(tableDF.getSelectedRow(), 2), (String)tableDF.getValueAt(tableDF.getSelectedRow(), 3));
            txtNombreD.setText(df.getNombre());
            txtApellidoD.setText(df.getApellido());
            txtDireccionD.setText(df.getDireccion());
            txtNITD.setText(df.getNit());
            btnAgregarD.setText("EDITAR");
            btnCancelarDF.setVisible(true);
            datosFE = (String)tableDF.getValueAt(tableDF.getSelectedRow(), 2);
        }
    }//GEN-LAST:event_tableDFMouseClicked

    private void btnCancelarDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarDFActionPerformed
        btnAgregarD.setText("AGREGAR");
        btnCancelarDF.setVisible(false);
        LimpiarTextField();
        tableDF.clearSelection();
    }//GEN-LAST:event_btnCancelarDFActionPerformed
     
    // METODOS PARA TARJETAS
    private boolean ValidarTextField() {
        if(!txtNombre.getText().isEmpty() && !txtNumero.getText().isEmpty() && !txtFecha.getText().isEmpty() && (opDebito.isSelected() || opCredito.isSelected())) {
            return true;
        }
        return false;
    }
    
    private void LimpiarTextField() {
        txtNombre.setText("");
        txtNumero.setText("");
        txtFecha.setText("");
        tipo.clearSelection();
        txtNombreD.setText("");
        txtApellidoD.setText("");
        txtDireccionD.setText("");
        txtNITD.setText("");
    }
    
    private void LlenarTabla() {
        DefaultTableModel modelo = new DefaultTableModel(new String[]{"NO.", "NOMBRE", "NUMERO", "TIPO", "FECHA"}, controladorT.ObtenerTarjetasUsuario().size());
        tableT.setModel(modelo);
        
        TableModel modeloDatos = tableT.getModel();
        for(int i = 0; i < controladorT.ObtenerTarjetasUsuario().size(); i++) {
            Tarjetas tarjeta = controladorT.ObtenerTarjetasUsuario().get(i);
            modeloDatos.setValueAt(i+1, i, 0);
            modeloDatos.setValueAt(tarjeta.getNombre(), i, 1);
            modeloDatos.setValueAt(tarjeta.getNumero(), i, 2);
            modeloDatos.setValueAt(tarjeta.getTipo(), i, 3);
            modeloDatos.setValueAt(tarjeta.getFecha(), i, 4);
        }  
    }
    
    // METODOS PARA DATOS FACTURACION
    
    private boolean ValidarCampos() {
        if(!txtNombreD.getText().isEmpty() && !txtApellidoD.getText().isEmpty() && !txtDireccionD.getText().isEmpty() && !txtNITD.getText().isEmpty()) {
            return true;
        }
        return false;
    }
    
    private void LlenarTablaDatos() {
        DefaultTableModel modelo = new DefaultTableModel(new String[]{"NO.", "NOMBRE COMPLETO", "DIRECCIÓN", "NIT"}, controladorDF.ObtenerDatos().size());
        tableDF.setModel(modelo);
        
        TableModel modeloDatos = tableDF.getModel();
        for(int i = 0; i < controladorDF.ObtenerDatos().size(); i++) {
            DatosFacturacion datos = controladorDF.ObtenerDatos().get(i);
            modeloDatos.setValueAt(i+1, i, 0);
            modeloDatos.setValueAt(datos.getNombre()+" "+datos.getApellido(), i, 1);
            modeloDatos.setValueAt(datos.getDireccion(), i, 2);
            modeloDatos.setValueAt(datos.getNit(), i, 3);
        }  
    }
    
    // METODOS PARA COTIZACIÓN
    
    private void DatosIniciales() {
        cmbDO.addItem("DEPARTAMENTO");
        cmbDD.addItem("DEPARTAMENTO");
        //if(!cmbMO.getItemAt(0).equals("MUNICIPIO") || !cmbMD.getItemAt(0).equals("MUNICIPIO")) {
            cmbMO.addItem("MUNICIPIO");
            cmbMD.addItem("MUNICIPIO");
        //}

        for(int i=0; i < controladorD.ObtenerDepartamento().size(); i++) {
            cmbDO.addItem(controladorD.ObtenerDepartamento().get(i).getNombre());
            cmbDD.addItem(controladorD.ObtenerDepartamento().get(i).getNombre());
        }
        
        // DATOS DE PAGO VISIBLES        
        lblTarjeta.setVisible(false);
        cmbTarjeta.setVisible(false);
        lblCVV.setVisible(false);
        txtCVV.setVisible(false);
        btnCancelar.setVisible(false);
        
        cmbDatosF.addItem("SELECCIONA UN DATO");
        cmbTarjeta.addItem("SELECCIONA UNA TARJETA");
        
        DatosFacturacion();
        DatosTarjeta();
    }
    
    private void DatosComboboxMunicipio(JComboBox cmb, String nombre) {
        
        if(!nombre.equals("DEPARTAMENTO")) {
            cmb.removeAllItems();
            cmb.addItem("MUNICIPIO");
            String codigoD = controladorD.ObtenerDepartamentoNombre(nombre).getCodigoDepartamento();
            controladorM.MunicipiosPorDepartamento(codigoD);
            for(int i=0; i < controladorM.ObtenerMunicipios().size(); i++) {
                cmb.addItem(controladorM.ObtenerMunicipios().get(i).getNombre());
            }
            
        } else {
            cmb.removeAllItems();
            cmb.addItem("MUNICIPIO");
        }
        
    }
    
    private boolean ValidarCamposCotizar() {
        if(!txtDO.getText().isEmpty() && !txtDD.getText().isEmpty() && cmbDO.getSelectedIndex() != 0 && cmbMO.getSelectedIndex() != 0 && !txtDO.getText().isEmpty() && cmbDD.getSelectedIndex() != 0 && cmbMD.getSelectedIndex() != 0 && (Integer)spinner.getValue() >= 1 && (opPequenio.isSelected() || opMediano.isSelected() || opGrande.isSelected()) && (tipoServicio.getSelection() != null)) {
            btnCancelar.setVisible(true);
            return true;
        }
        return false;
    }
    
    private void ValoresRadio() {
        btnDescargarC.setVisible(false);
        btnCancelarEnvio.setVisible(false);
        opPequenio.setActionCommand("Pequeño");
        opMediano.setActionCommand("Mediano");
        opGrande.setActionCommand("Grande");
        opEstandar.setActionCommand("Estándar");
        opEspecial.setActionCommand("Especial");
        opPContraEntrega.setActionCommand("Contra entrega");
        opPConTarjeta.setActionCommand("Con tarjeta");
        btnFactura.setVisible(false);
        btnGuia.setVisible(false);
        btnCancelarDF.setVisible(false);
    }   
    
    private void PrecioServicio() {
        if(!cmbDD.getSelectedItem().equals("DEPARTAMENTO")) {
            opEstandar.setText("Estándar (Q "+controladorR.ObtenerRegionSeleccionada(controladorD.ObtenerDepartamentoNombre((String)cmbDD.getSelectedItem()).getCodigoRegion()).getEstandar()+")");
            opEspecial.setText("Especial (Q "+controladorR.ObtenerRegionSeleccionada(controladorD.ObtenerDepartamentoNombre((String)cmbDD.getSelectedItem()).getCodigoRegion()).getEspecial()+")");
        }
        
    }
    
    private void DatosFacturacion() {
        cmbDatosF.removeAllItems();
        cmbDatosF.addItem("SELECCIONA UN DATO");
        for(int i=0; i < controladorDF.ObtenerDatos().size(); i++) {
            cmbDatosF.addItem(controladorDF.ObtenerDatos().get(i).getNombre()+" "+controladorDF.ObtenerDatos().get(i).getApellido()+", "+controladorDF.ObtenerDatos().get(i).getDireccion());
        }
    }
    
    private void DatosTarjeta() {
        cmbTarjeta.removeAllItems();
        cmbTarjeta.addItem("SELECCIONA UNA TARJETA");
        for(int i=0; i < controladorT.ObtenerTarjetasUsuario().size(); i++) {
            cmbTarjeta.addItem(controladorT.ObtenerTarjetasUsuario().get(i).getNumero());
        }
    }
    
    private void HabilitarPanel(Container container, boolean enable) {
        Component[] components = container.getComponents();
        for (Component component : components) {
            component.setEnabled(enable);
            if (component instanceof Container) {
                HabilitarPanel((Container)component, enable);
            }
        }
}
    
    private void LimpiarTextFieldCotizar() {
        cmbDO.setSelectedIndex(0);
        cmbMO.removeAllItems();
        cmbDD.setSelectedIndex(0);
        cmbMD.removeAllItems();
        txtDO.setText("");
        txtDD.setText("");
        tamanioP.clearSelection();
        spinner.setValue(0);
        tipoServicio.clearSelection();
        tipoPago.clearSelection();
        cmbDatosF.setSelectedIndex(0);
        txtCVV.setText("");
        cmbTarjeta.setSelectedIndex(0);
        opEstandar.setText("Estándar (Q 00.00)");
        opEspecial.setText("Especial (Q 00.00)");
    }
    
    private boolean ValidarCamposPago() {     
        if(opPContraEntrega.isSelected() || opPConTarjeta.isSelected()) {
            if(tipoPago.getSelection().getActionCommand().equalsIgnoreCase("Contra entrega")) {
                if(cmbDatosF.getSelectedIndex() != 0) {
                    return true;
                }
            } else if(tipoPago.getSelection().getActionCommand().equalsIgnoreCase("Con tarjeta")){
                if(cmbDatosF.getSelectedIndex() != 0 && cmbTarjeta.getSelectedIndex() != 0 && !txtCVV.getText().isEmpty()) {
                    if(txtCVV.getText().length() == 3) {
                        return true;
                    }
                }
            }
            
            
        }     
        return false;
    }
    
    // METODOS VISTA ENVIOS
    
    private void LlenarTablaEnvios() {
        DefaultTableModel modelo = new DefaultTableModel(new String[]{"NO.", "CÓDIGO", "TIPO SERVICIO", "DEPARTAMENTO DESTINO", "MUNICIPIO DESTINO", "TIPO DE PAGO", "TOTAL DE ENVÍO"}, controladorC.ObtenerComprasUsuario().size());
        tableE.setModel(modelo);
        
        TableModel modeloDatos = tableE.getModel();
        for(int i = 0; i < controladorC.ObtenerComprasUsuario().size(); i++) {
            Compras envio = controladorC.ObtenerComprasUsuario().get(i);
            modeloDatos.setValueAt(i+1, i, 0);
            modeloDatos.setValueAt(envio.getIdPaquete(), i, 1);
            modeloDatos.setValueAt(envio.getTipoServicio(), i, 2);
            modeloDatos.setValueAt(envio.getDepartamentoD(), i, 3);
            modeloDatos.setValueAt(envio.getMunicipioD(), i, 4);
            modeloDatos.setValueAt(envio.getTipoPago(), i, 5);
            modeloDatos.setValueAt(envio.getTotal(), i, 6);
        }  
    }
    
    private void setImageLabel(JLabel labelName, String root) {
        image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(), Image.SCALE_DEFAULT));
        labelName.setIcon(icon);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregarD;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelarDF;
    private javax.swing.JButton btnCancelarEnvio;
    private javax.swing.JButton btnCotizar;
    private javax.swing.JButton btnDescargarC;
    private javax.swing.JButton btnFactura;
    private javax.swing.JButton btnGuia;
    private javax.swing.JButton btnPago;
    private javax.swing.JComboBox<String> cmbDD;
    private javax.swing.JComboBox<String> cmbDO;
    private javax.swing.JComboBox<String> cmbDatosF;
    private javax.swing.JComboBox<String> cmbMD;
    private javax.swing.JComboBox<String> cmbMO;
    private javax.swing.JComboBox<String> cmbTarjeta;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCVV;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblSaludo;
    private javax.swing.JLabel lblTarjeta;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JRadioButton opCredito;
    private javax.swing.JRadioButton opDebito;
    private javax.swing.JRadioButton opEspecial;
    private javax.swing.JRadioButton opEstandar;
    private javax.swing.JRadioButton opGrande;
    private javax.swing.JRadioButton opMediano;
    private javax.swing.JRadioButton opPConTarjeta;
    private javax.swing.JRadioButton opPContraEntrega;
    private javax.swing.JRadioButton opPequenio;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JPanel panel4;
    private javax.swing.JPanel panelPago;
    private javax.swing.JSpinner spinner;
    private javax.swing.JTabbedPane tabbed;
    private javax.swing.JTable tableDF;
    private javax.swing.JTable tableE;
    private javax.swing.JTable tableT;
    private javax.swing.ButtonGroup tamanioP;
    private javax.swing.ButtonGroup tipo;
    private javax.swing.ButtonGroup tipoPago;
    private javax.swing.ButtonGroup tipoServicio;
    private javax.swing.JTextField txtApellidoD;
    private javax.swing.JTextField txtCVV;
    private javax.swing.JTextField txtDD;
    private javax.swing.JTextField txtDO;
    private javax.swing.JTextField txtDireccionD;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNITD;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreD;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
