package proyecto1.vista;

import java.awt.Color;
import java.awt.Image;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import proyecto1.controlador.ControladorKiosco;
import proyecto1.controlador.ControladorUsuario;

/**
 *
 * @author JD
 */
public class Perfil extends javax.swing.JFrame {

    /**
     * Creates new form Perfil
     */
    ControladorUsuario usuario = new ControladorUsuario();
    JFileChooser fc = new JFileChooser();
    ImageIcon image;
    String imageUser = usuario.UsuarioLogeado().getFoto();
    ControladorKiosco controladorK = new ControladorKiosco();
    public Perfil() {
        initComponents();
        asignarItems();
        setImageLabel(lblIma, imageUser);
        DatosKiosco();
        RellenarCampos();
        setVisibleLbl(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genero = new javax.swing.ButtonGroup();
        jLabel9 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        opMujer = new javax.swing.JRadioButton();
        opHombre = new javax.swing.JRadioButton();
        cmbNacionalidad = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        lblImagen = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        btnImagen = new javax.swing.JButton();
        lblIma = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cmbRol = new javax.swing.JComboBox<>();
        cmbKiosco = new javax.swing.JComboBox<>();
        lblKiosco = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        lblRNombre = new javax.swing.JLabel();
        txtNombreP = new javax.swing.JTextField();
        lblRApellido = new javax.swing.JLabel();
        lblRDPI = new javax.swing.JLabel();
        lblRCorreo = new javax.swing.JLabel();
        lblRUsuario = new javax.swing.JLabel();
        lblRTele = new javax.swing.JLabel();
        lblRContra = new javax.swing.JLabel();
        lblRPass = new javax.swing.JLabel();
        lblRRol = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtApellidoP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDPIP = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        txtRPass = new javax.swing.JPasswordField();
        lblRFecha = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblRGenero = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblRNacionalidad = new javax.swing.JLabel();
        lblCampos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel9.setText("Telefono");

        jLabel10.setText("Fecha de nacimiento (dd-mm-yyyy)");

        jLabel11.setText("Genero");

        genero.add(opMujer);
        opMujer.setText("Mujer");
        opMujer.setBorder(null);
        opMujer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opMujerActionPerformed(evt);
            }
        });

        genero.add(opHombre);
        opHombre.setText("Hombre");

        jLabel12.setText("Nacionalidad");

        txtFecha.setToolTipText("Mes");

        lblImagen.setText("Imagen");

        btnEditar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnEditar.setText("EDITAR");
        btnEditar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnEditarFocusLost(evt);
            }
        });
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnRegresar.setText("REGRESAR");
        btnRegresar.setFocusPainted(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnImagen.setText("Subir");
        btnImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagenActionPerformed(evt);
            }
        });

        jLabel13.setText("Rol");

        cmbRol.setEnabled(false);
        cmbRol.setFocusable(false);
        cmbRol.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbRolItemStateChanged(evt);
            }
        });
        cmbRol.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbRolFocusLost(evt);
            }
        });
        cmbRol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbRolMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmbRolMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cmbRolMousePressed(evt);
            }
        });
        cmbRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRolActionPerformed(evt);
            }
        });

        lblKiosco.setText("Kioscos");

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("MI PERFIL");

        jLabel2.setText("Correo");

        txtCorreo.setEnabled(false);
        txtCorreo.setFocusable(false);

        jLabel3.setText("Nombre");

        lblRNombre.setForeground(new java.awt.Color(255, 0, 0));
        lblRNombre.setText("*");

        lblRApellido.setForeground(new java.awt.Color(255, 0, 0));
        lblRApellido.setText("*");

        lblRDPI.setForeground(new java.awt.Color(255, 0, 0));
        lblRDPI.setText("*");

        lblRCorreo.setForeground(new java.awt.Color(255, 0, 0));
        lblRCorreo.setText("*");

        lblRUsuario.setForeground(new java.awt.Color(255, 0, 0));
        lblRUsuario.setText("*");

        lblRTele.setForeground(new java.awt.Color(255, 0, 0));
        lblRTele.setText("*");

        lblRContra.setForeground(new java.awt.Color(255, 0, 0));
        lblRContra.setText("*");

        lblRPass.setForeground(new java.awt.Color(255, 0, 0));
        lblRPass.setText("*");

        lblRRol.setForeground(new java.awt.Color(255, 0, 0));
        lblRRol.setText("*");

        jLabel4.setText("Apellido");

        jLabel5.setText("DPI");

        jLabel6.setText("Contraseña");

        jLabel7.setText("Reingresar contraseña");

        txtRPass.setToolTipText("");

        lblRFecha.setForeground(new java.awt.Color(255, 0, 0));
        lblRFecha.setText("*");

        jLabel8.setText("Usuario");

        lblRGenero.setForeground(new java.awt.Color(255, 0, 0));
        lblRGenero.setText("*");

        lblRNacionalidad.setForeground(new java.awt.Color(255, 0, 0));
        lblRNacionalidad.setText("*");

        lblCampos.setForeground(new java.awt.Color(255, 0, 0));
        lblCampos.setText("* Campos requeridos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEditar)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(lblCampos)
                .addGap(156, 156, 156))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnRegresar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel3)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(lblRNombre))
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel2)
                                                .addComponent(txtNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel4)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(lblRApellido))
                                                .addComponent(txtApellidoP)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addGap(0, 0, Short.MAX_VALUE)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblRDPI, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(lblRCorreo, javax.swing.GroupLayout.Alignment.TRAILING)))))
                                        .addComponent(txtDPIP)
                                        .addComponent(txtCorreo)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel6)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(lblRContra))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel8)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(lblRUsuario))
                                                .addComponent(txtUsuario)
                                                .addComponent(txtPass)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel13)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(lblRRol))
                                                .addComponent(cmbRol, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(24, 24, 24)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtTelefono, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel9)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(lblRTele))
                                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtRPass)
                                                .addComponent(lblKiosco)
                                                .addComponent(cmbKiosco, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblRPass)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cmbNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING))
                                                        .addGap(55, 55, 55)
                                                        .addComponent(lblRFecha))
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(lblRGenero)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(opMujer)
                                                            .addGap(39, 39, 39)
                                                            .addComponent(opHombre)))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel12)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(lblRNacionalidad)))
                                                .addGap(63, 63, 63))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblImagen)
                                                .addGap(258, 258, 258)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnImagen)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblIma, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(41, 41, 41))))))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(57, 57, 57)
                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 349, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblCampos)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnRegresar)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(24, 24, 24)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(lblRFecha))
                            .addGap(49, 49, 49)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(lblRGenero))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(opMujer)
                                .addComponent(opHombre))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(17, 17, 17)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel12)
                                        .addComponent(lblRNacionalidad))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cmbNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblImagen))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(105, 105, 105)
                                    .addComponent(lblIma, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(lblRApellido))
                                .addComponent(lblRNombre, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(lblRDPI, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtDPIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(lblRCorreo)))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)
                                .addComponent(lblRUsuario)
                                .addComponent(lblRTele))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(lblRContra)
                                .addComponent(lblRPass))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtRPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnImagen))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13)
                                .addComponent(lblKiosco)
                                .addComponent(lblRRol))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cmbRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmbKiosco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(94, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void opMujerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opMujerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opMujerActionPerformed

    private void btnEditarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnEditarFocusLost
        
    }//GEN-LAST:event_btnEditarFocusLost

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        String pass;
        if(cmbRol.getSelectedItem().equals("Kiosco")) {
            if (!txtNombreP.getText().isEmpty() && !txtApellidoP.getText().isEmpty() && !txtDPIP.getText().isEmpty() && !txtCorreo.getText().isEmpty() && !txtUsuario.getText().isEmpty() && !txtTelefono.getText().isEmpty() && cmbRol.getSelectedIndex() != 0 && !txtFecha.getText().isEmpty() && cmbNacionalidad.getSelectedIndex() != 0 && (opMujer.isSelected() || opHombre.isSelected()) && cmbKiosco.getSelectedIndex() != 0 ) {
                if(txtPass.getText().equals("") && txtRPass.getText().equals("")) {
                    pass = usuario.UsuarioLogeado().getPassword();
                } else {
                    pass = txtPass.getText();
                }
                if(usuario.ValidarPassword(pass)) {
                    if(txtPass.getText().equals(txtRPass.getText())) {
                        usuario.EditarUsuarioKiosco(txtNombreP.getText(), txtApellidoP.getText(), pass, txtDPIP.getText(), txtFecha.getText(), genero.getSelection().getActionCommand(), (String)cmbNacionalidad.getSelectedItem(), txtUsuario.getText(), txtTelefono.getText(), imageUser, (String)cmbKiosco.getSelectedItem());
                        JOptionPane.showMessageDialog(this, "Usuario editado.");
                        RellenarCampos();
                    } else {
                        JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden.");
                    }

                }else {
                    JOptionPane.showMessageDialog(this, "La contraseña debe tener al menos una Mayuscula, minuscula, numero, caracter especial.");
                }
            } else {
                setVisibleLbl(true);
            }
        } else {
            if (!txtNombreP.getText().isEmpty() && !txtApellidoP.getText().isEmpty() && !txtDPIP.getText().isEmpty() && !txtCorreo.getText().isEmpty() && !txtUsuario.getText().isEmpty() && !txtTelefono.getText().isEmpty() && cmbRol.getSelectedIndex() != 0 && !txtFecha.getText().isEmpty() && cmbNacionalidad.getSelectedIndex() != 0 && (opMujer.isSelected() || opHombre.isSelected()) ) {
                if(txtPass.getText().equals("") && txtRPass.getText().equals("")) {
                    pass = usuario.UsuarioLogeado().getPassword();
                } else {
                    pass = txtPass.getText();
                }
                if(usuario.ValidarPassword(pass)) {
                    
                    if(txtPass.getText().equals(txtRPass.getText())) {
                        usuario.EditarUsuarioCliente(txtNombreP.getText(), txtApellidoP.getText(), pass, txtDPIP.getText(), txtFecha.getText(), genero.getSelection().getActionCommand(), (String)cmbNacionalidad.getSelectedItem(), txtUsuario.getText(), txtTelefono.getText(), imageUser);
                        JOptionPane.showMessageDialog(this, "Usuario editado.");
                        RellenarCampos();
                    } else {
                        JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden.");
                    }

                }else {
                    JOptionPane.showMessageDialog(this, "La contraseña debe tener al menos una Mayuscula, minuscula, numero, caracter especial.");
                }
            } else {
                setVisibleLbl(true);
            }
        }

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.setVisible(false);
        MenuCliente vistaC = new MenuCliente();
        vistaC.setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagenActionPerformed
        fc.setDialogTitle("Buscar foto");

        if(fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            imageUser = fc.getSelectedFile().toString();
            lblIma.setBorder(BorderFactory.createLineBorder(Color.BLACK, 2));
            setImageLabel(lblIma, imageUser);
        }
    }//GEN-LAST:event_btnImagenActionPerformed

    private void cmbRolItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbRolItemStateChanged

    }//GEN-LAST:event_cmbRolItemStateChanged

    private void cmbRolFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbRolFocusLost
        if(cmbRol.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar una opción valida en el rol.");
        }
    }//GEN-LAST:event_cmbRolFocusLost

    private void cmbRolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbRolMouseClicked

    }//GEN-LAST:event_cmbRolMouseClicked

    private void cmbRolMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbRolMouseExited

    }//GEN-LAST:event_cmbRolMouseExited

    private void cmbRolMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbRolMousePressed

    }//GEN-LAST:event_cmbRolMousePressed

    private void cmbRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRolActionPerformed
        if(cmbRol.getSelectedItem().equals("Kiosco")) {
            lblKiosco.setVisible(true);
            cmbKiosco.setVisible(true);
        }else {
            lblKiosco.setVisible(false);
            cmbKiosco.setVisible(false);
        }
    }//GEN-LAST:event_cmbRolActionPerformed

    private void RellenarCampos() {
        txtNombreP.setText(usuario.UsuarioLogeado().getNombre());
        txtApellidoP.setText(usuario.UsuarioLogeado().getApellido());
        txtDPIP.setText(usuario.UsuarioLogeado().getDpi());
        txtCorreo.setText(usuario.UsuarioLogeado().getCorreo());
        txtUsuario.setText(usuario.UsuarioLogeado().getUsuario());
        txtTelefono.setText(usuario.UsuarioLogeado().getTelefono());
        cmbRol.setSelectedItem(usuario.UsuarioLogeado().getRol());
        cmbKiosco.setSelectedItem(usuario.UsuarioLogeado().getCodigoKiosco());
        txtFecha.setText(usuario.UsuarioLogeado().getFechaC());
        cmbNacionalidad.setSelectedItem(usuario.UsuarioLogeado().getNacionalidad());
        if(usuario.UsuarioLogeado().getGenero().equals("Hombre")) {
           genero.setSelected(opHombre.getModel(), true);
        } else if (usuario.UsuarioLogeado().getGenero().equals("Mujer")) {
            genero.setSelected(opMujer.getModel(), true);
        }
    }
    
    private void asignarItems() {
        cmbNacionalidad.addItem("Seleccione una opción");
        cmbNacionalidad.addItem("guatemalteco");
        cmbNacionalidad.addItem("salvadoreño");
        cmbNacionalidad.addItem("hondureño");
        cmbNacionalidad.addItem("nicaragüense");
        cmbNacionalidad.addItem("costarricense");
        
        cmbRol.addItem("Seleccione una opción");
        cmbRol.addItem("Individual");
        cmbRol.addItem("Kiosco");
        
        opHombre.setActionCommand("Hombre");
        opMujer.setActionCommand("Mujer");
    }
    
    private void DatosKiosco() {
        cmbKiosco.addItem("SELECCIONA UN KIOSCO");
        for(int i=0; i < controladorK.ObtenerKioscos().size(); i++) {
            cmbKiosco.addItem(controladorK.ObtenerKioscos().get(i).getCodigo());
        }
    }
    
    private void setVisibleLbl(boolean bln) {
        lblCampos.setVisible(bln);
        lblRNombre.setVisible(bln);
        lblRApellido.setVisible(bln);
        lblRCorreo.setVisible(bln);
        lblRDPI.setVisible(bln);
        lblRUsuario.setVisible(bln);
        lblRTele.setVisible(bln);
        lblRRol.setVisible(bln);
        lblRContra.setVisible(bln);
        lblRPass.setVisible(bln);
        lblRFecha.setVisible(bln);
        lblRGenero.setVisible(bln);
        lblRNacionalidad.setVisible(bln);
    }
    
    private void setImageLabel(JLabel labelName, String root) {
        image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(), Image.SCALE_DEFAULT));
        labelName.setIcon(icon);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Perfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnImagen;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cmbKiosco;
    private javax.swing.JComboBox<String> cmbNacionalidad;
    private javax.swing.JComboBox<String> cmbRol;
    private javax.swing.ButtonGroup genero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCampos;
    private javax.swing.JLabel lblIma;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblKiosco;
    private javax.swing.JLabel lblRApellido;
    private javax.swing.JLabel lblRContra;
    private javax.swing.JLabel lblRCorreo;
    private javax.swing.JLabel lblRDPI;
    private javax.swing.JLabel lblRFecha;
    private javax.swing.JLabel lblRGenero;
    private javax.swing.JLabel lblRNacionalidad;
    private javax.swing.JLabel lblRNombre;
    private javax.swing.JLabel lblRPass;
    private javax.swing.JLabel lblRRol;
    private javax.swing.JLabel lblRTele;
    private javax.swing.JLabel lblRUsuario;
    private javax.swing.JRadioButton opHombre;
    private javax.swing.JRadioButton opMujer;
    private javax.swing.JTextField txtApellidoP;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDPIP;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNombreP;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JPasswordField txtRPass;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
