/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1.vista;

import proyecto1.controlador.ControladorCompra;

/**
 *
 * @author JD
 */
public class Reportes extends javax.swing.JFrame {

    /**
     * Creates new form Reportes
     */
    
    ControladorCompra controladorC = new ControladorCompra();
    
    public Reportes() {
        initComponents();
        tab.setSelectedIndex(4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnRegion = new javax.swing.JButton();
        btnPaquete = new javax.swing.JButton();
        btnIngresos = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tab = new javax.swing.JTabbedPane();
        panelR = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelP = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblPaquetes = new javax.swing.JLabel();
        panelI = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblIngresos = new javax.swing.JLabel();
        panelU = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegresar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 19, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("REPORTES");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 12, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 50, 667, 10));

        btnRegion.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnRegion.setText("REGIONES");
        btnRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegionActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegion, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 90, 125, -1));

        btnPaquete.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnPaquete.setText("PAQUETES");
        btnPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaqueteActionPerformed(evt);
            }
        });
        getContentPane().add(btnPaquete, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 88, 125, -1));

        btnIngresos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnIngresos.setText("INGRESOS");
        btnIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresosActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 88, 125, -1));

        btnUsuarios.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnUsuarios.setText("USUARIOS");
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(btnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 88, 125, -1));

        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("SELECCIONA EL REPORTE");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 150, 600, 39));

        tab.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jLabel2.setText("lbl1");

        javax.swing.GroupLayout panelRLayout = new javax.swing.GroupLayout(panelR);
        panelR.setLayout(panelRLayout);
        panelRLayout.setHorizontalGroup(
            panelRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRLayout.createSequentialGroup()
                .addContainerGap(340, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(297, 297, 297))
        );
        panelRLayout.setVerticalGroup(
            panelRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRLayout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jLabel2)
                .addContainerGap(294, Short.MAX_VALUE))
        );

        tab.addTab("tab1", panelR);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel4.setText("CANTIDAD DE PAQUETES");

        lblPaquetes.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblPaquetes.setText("0 PAQUETES");

        javax.swing.GroupLayout panelPLayout = new javax.swing.GroupLayout(panelP);
        panelP.setLayout(panelPLayout);
        panelPLayout.setHorizontalGroup(
            panelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPLayout.createSequentialGroup()
                .addGroup(panelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel4))
                    .addGroup(panelPLayout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(lblPaquetes)))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        panelPLayout.setVerticalGroup(
            panelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel4)
                .addGap(39, 39, 39)
                .addComponent(lblPaquetes)
                .addContainerGap(299, Short.MAX_VALUE))
        );

        tab.addTab("tab2", panelP);

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel6.setText("EL TOTAL DE INGRESOS ES DE:");

        lblIngresos.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblIngresos.setText("Q 00.00");

        javax.swing.GroupLayout panelILayout = new javax.swing.GroupLayout(panelI);
        panelI.setLayout(panelILayout);
        panelILayout.setHorizontalGroup(
            panelILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelILayout.createSequentialGroup()
                .addGroup(panelILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelILayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel6))
                    .addGroup(panelILayout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(lblIngresos)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        panelILayout.setVerticalGroup(
            panelILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelILayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel6)
                .addGap(60, 60, 60)
                .addComponent(lblIngresos)
                .addContainerGap(272, Short.MAX_VALUE))
        );

        tab.addTab("tab3", panelI);

        jLabel5.setText("lbl4");
        jLabel5.setToolTipText("");

        javax.swing.GroupLayout panelULayout = new javax.swing.GroupLayout(panelU);
        panelU.setLayout(panelULayout);
        panelULayout.setHorizontalGroup(
            panelULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelULayout.createSequentialGroup()
                .addContainerGap(390, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(247, 247, 247))
        );
        panelULayout.setVerticalGroup(
            panelULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelULayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel5)
                .addContainerGap(373, Short.MAX_VALUE))
        );

        tab.addTab("tab4", panelU);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 653, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );

        tab.addTab("tab5", jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(tab)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(tab, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 199, 670, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.setVisible(false);
        MenuPrincipal menu = new MenuPrincipal();
        menu.setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaqueteActionPerformed
        lblTitulo.setText("Número total de paquetes enviados");
        tab.setSelectedIndex(1);
        lblPaquetes.setText(String.valueOf(controladorC.ObtenerPaquetes())+" PAQUETES");
    }//GEN-LAST:event_btnPaqueteActionPerformed

    private void btnIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresosActionPerformed
        lblTitulo.setText("Ingresos totales");
        tab.setSelectedIndex(2);
        lblIngresos.setText("Q "+String.valueOf(controladorC.ObtenerIngreso()));
    }//GEN-LAST:event_btnIngresosActionPerformed

    private void btnRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegionActionPerformed
        lblTitulo.setText("Lista de regiones con más envíos");
        tab.setSelectedIndex(0);
    }//GEN-LAST:event_btnRegionActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        lblTitulo.setText("Lista de usuarios con más paquetes enviados.");
        tab.setSelectedIndex(3);
    }//GEN-LAST:event_btnUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresos;
    private javax.swing.JButton btnPaquete;
    private javax.swing.JButton btnRegion;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblIngresos;
    private javax.swing.JLabel lblPaquetes;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelI;
    private javax.swing.JPanel panelP;
    private javax.swing.JPanel panelR;
    private javax.swing.JPanel panelU;
    private javax.swing.JTabbedPane tab;
    // End of variables declaration//GEN-END:variables
}
